# Generated by Django 5.0.3 on 2024-04-05 01:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CAI', 'Curso de Aprendizagem Industrial'), ('CT', 'Curso Técnico'), ('CST', 'Custo Superior'), ('FIC', 'FalleN')], max_length=100)),
                ('duration', models.IntegerField()),
                ('durationType', models.CharField(choices=[('H', 'Horas'), ('S', 'Semestre')], max_length=100)),
                ('area', models.CharField(choices=[('TI', 'Tecnologia da Informação'), ('MEC', 'Mecanica'), ('ElÉTRIC', 'Elétrica')], max_length=100)),
                ('modality', models.CharField(choices=[('EAD', 'Ensino a Distância'), ('PRE', 'Presencial'), ('HIB', 'Hibrido')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetDate', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('CAI', 'Curso de Aprendizagem Industrial'), ('CT', 'Curso Técnico'), ('CST', 'Custo Superior'), ('FIC', 'FalleN')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Environments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block', models.CharField(choices=[('A', 'Bloco A'), ('B', 'Bloco B'), ('C', 'Bloco C')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timeLoad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrationNumber', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassesDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classFKClassesDivision', to='main.classes')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='courseFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_class', to='main.courses'),
        ),
        migrations.CreateModel(
            name='CoursesThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curseFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesThemesCourse', to='main.courses')),
                ('themeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesThemesTheme', to='main.themes')),
            ],
        ),
        migrations.CreateModel(
            name='EnviromentsAssignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigneeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviromentsAssigneesCustomUser', to=settings.AUTH_USER_MODEL)),
                ('environmentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviromentsAssigneesEnvironment', to='main.environments')),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('assigneeFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipmentsCustomUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Cancelado'), ('1', 'Pendente'), ('2', 'Em Aprovação'), ('3', 'Aprovado'), ('4', 'Em Revisão')], default='1', max_length=100)),
                ('CoursesThemesFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planCursesThemesFK', to='main.coursesthemes')),
                ('CustomUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planCustomUserFK', to=settings.AUTH_USER_MODEL)),
                ('approverFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planApproverFK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('0', 'Cancelado'), ('1', 'Pendente'), ('2', 'Em Aprovação'), ('3', 'Aprovado'), ('4', 'Em Revisão')], max_length=20)),
                ('comment', models.CharField(max_length=500)),
                ('file', models.CharField(max_length=200)),
                ('planFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planStatusPlanFK', to='main.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Signature', models.CharField(max_length=200)),
                ('creationDate', models.DateTimeField(auto_now=True)),
                ('ownerFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signaturesCustomUserFk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='signatureFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planSignatureFK', to='main.signatures'),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=2000)),
                ('diagnostic', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(choices=[('MA', 'Manutenção'), ('ME', 'Melhoria')], max_length=100)),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('EA', 'Em Andamento'), ('CA', 'Cancela'), ('CO', 'Concluída'), ('EN', 'Encerrada')], max_length=100)),
                ('environmentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksEnvironments', to='main.environments')),
                ('reporterFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksCustomUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TasksAssignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigneeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksAssignees', to=settings.AUTH_USER_MODEL)),
                ('taskFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksAssigneesTask', to='main.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TasksEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksEquipmentsEquipmentt', to='main.equipments')),
                ('taskFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksEquipmentssTask', to='main.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TasksStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('EA', 'Em Andamento'), ('CA', 'Cancela'), ('CO', 'Concluída'), ('EN', 'Encerrada')], max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=300)),
                ('taskFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksAssigneesTaskk', to='main.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='FilesTasksStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000)),
                ('equipamentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileTasksStatusEquipamentFk', to='main.tasksequipments')),
                ('taskStatusFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filesTasksStatusTask', to='main.tasksstatus')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAlocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('alocationStatus', models.CharField(choices=[('1', 'Rascunho'), ('2', 'Assinalado'), ('3', 'Concluido')], default='1', max_length=100)),
                ('CustomUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherAlocationDetailCustomUserFK', to=settings.AUTH_USER_MODEL)),
                ('classDivisionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachetAlocationDetailClassDivisionFK', to='main.classesdivision')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAlocationDetailEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDay', models.CharField(choices=[('Seg', 'Segunda-Feira'), ('Ter', 'Terça-Feira'), ('Qua', 'Quarta-Feira'), ('Qui', 'Quinta-Feira'), ('Sex', 'Sexta-Feira'), ('Sab', 'Sabado'), ('Dom', 'Domingo')], max_length=30)),
                ('hourStart', models.TimeField()),
                ('hourEnd', models.TimeField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('enviromentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherAlocationDetailEnviromentFK', to='main.environments')),
                ('teacherAlocationDetailFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherAlocationDetailFK', to='main.teacheralocationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersAlocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherAlocationClassFK', to='main.classes')),
                ('reporterFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherAlocationReporterFkK', to=settings.AUTH_USER_MODEL)),
                ('ThemeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherAlocationThemeFK1', to='main.themes')),
            ],
        ),
    ]
